# Generated by Django 4.1.5 on 2023-01-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_of_board',
            field=models.CharField(choices=[('mercosur', 'Mercosur'), ('old pattern', 'Old Pattern')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='board',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
