# Generated by Django 4.1.5 on 2023-01-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_car_parts_service_remove_client_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.client'),
        ),
        migrations.AddField(
            model_name='service',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.car'),
        ),
    ]
