# Generated by Django 4.1.5 on 2023-02-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_alter_car_client_alter_parts_car_alter_service_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
